<?php

namespace DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreditFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditFileRepository extends EntityRepository
{
}
