<?php

namespace DataBundle\Entity;

use Doctrine\ORM\EntityRepository;
use DataBundle\Entity\Offer;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository
{
    public function rejectByOfferAccepted(Offer $objOffer)
    {
        $this
                ->createQueryBuilder('o')
                ->update()
                ->set('o.status', Offer::STATUS_REJECTED)
                ->where('o.id <> :id')
                ->setParameter(':id', $objOffer->getId())
                ->andWhere('o.credit = :credit')
                ->setParameter('credit', $objOffer->getCredit())
                ->getQuery()
                ->execute();
    }
}
