services:
    apicontroller.listener:
        class: App\ApiBundle\EventListener\ApiKeyControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
