<?php

namespace App\GuardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuardGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuardGroupRepository extends EntityRepository
{
}
