services:
    beforecontroller.listener:
        class: App\GuardBundle\EventListener\BeforeControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
    my_custom.user_provider.email:
        class: App\GuardBundle\Security\EmailProvider
        public: false
        arguments: [@fos_user.user_manager]